"""
backend/simulator/models.py — Data Models and Telemetry Schemas for NOVA Plant Simulator.

Defines:
- Canonical 5-Bay plant topology and equipment hierarchies
- Equipment operational lifecycle states (RUNNING, STANDBY, STOPPED, FAULT, MAINTENANCE, TRIPPED)
- Strongly-typed synthetic TelemetryPoint schema with explicit provenance markings
- Industrial AlarmEvent schema with severity, state, and threshold tracking
- Aggregated SimulatorPlantState snapshot model
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class BayId(str, Enum):
    BAY_1 = "BAY-01"  # Feed & Preheat
    BAY_2 = "BAY-02"  # Cracking Furnaces (Primary Intelligence Bay)
    BAY_3 = "BAY-03"  # Transfer & Quench
    BAY_4 = "BAY-04"  # Compression & Separation
    BAY_5 = "BAY-05"  # Utilities & Safety


class EquipmentStatus(str, Enum):
    RUNNING = "RUNNING"
    STANDBY = "STANDBY"
    STOPPED = "STOPPED"
    FAULT = "FAULT"
    MAINTENANCE = "MAINTENANCE"
    TRIPPED = "TRIPPED"


class AlarmSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlarmState(str, Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    CLEARED = "CLEARED"


class TelemetryQuality(str, Enum):
    GOOD = "GOOD"
    UNCERTAIN = "UNCERTAIN"
    BAD = "BAD"


# ---------------------------------------------------------------------------
# Telemetry Schema
# ---------------------------------------------------------------------------

class TelemetryPoint(BaseModel):
    """
    Canonical Telemetry Event generated by the synthetic process simulator.
    Always maintains explicit synthetic markers and provenance metadata.
    """
    tag: str = Field(..., description="Instrument tag identifier (e.g. TI-201, FC-101)")
    value: float = Field(..., description="Numerical measured or calculated process value")
    unit: str = Field(..., description="Engineering unit (°C, MPa, kg/h, %, etc.)")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="UTC timestamp")
    quality: TelemetryQuality = Field(default=TelemetryQuality.GOOD, description="Sensor signal quality")
    equipment_id: str = Field(..., description="Associated equipment ID (e.g. F-201A, P-101A)")
    equipment_type: str = Field(..., description="Equipment category (furnace, pump, compressor, etc.)")
    unit_area: str = Field(default="UNIT-CRACK-01", description="Plant area code")
    bay_id: BayId = Field(default=BayId.BAY_2, description="Assigned physical plant bay")
    source: str = Field(default="synthetic_stream", description="Telemetry data source")
    is_synthetic: bool = Field(default=True, description="Strict synthetic data flag")
    provenance: Dict[str, Any] = Field(
        default_factory=lambda: {
            "generator": "NOVA_FiveBay_Process_Simulator",
            "model_lineage": "physics_correlated_synthetic",
        },
        description="Audit provenance metadata"
    )

    def to_observation_dict(self) -> Dict[str, Any]:
        """Convert to dictionary compatible with OperationalCase Observation model."""
        return {
            "tag": self.tag,
            "value": self.value,
            "unit": self.unit,
            "quality": self.quality.value,
            "description": f"{self.equipment_id} {self.tag}",
            "is_synthetic": self.is_synthetic,
            "timestamp": self.timestamp.isoformat(),
        }


# ---------------------------------------------------------------------------
# Alarm Schema
# ---------------------------------------------------------------------------

class AlarmEvent(BaseModel):
    """
    Industrial Alarm instance evaluated against process conditions.
    """
    alarm_id: str = Field(..., description="Unique alarm identifier (e.g. ALM-TI-201-AH)")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Alarm trip/update time")
    equipment_id: str = Field(..., description="Target equipment identifier")
    tag: str = Field(..., description="Triggering instrument tag")
    parameter_name: str = Field(..., description="Descriptive parameter name")
    severity: AlarmSeverity = Field(default=AlarmSeverity.WARNING, description="Alarm severity tier")
    state: AlarmState = Field(default=AlarmState.ACTIVE, description="Alarm lifecycle state")
    message: str = Field(..., description="Human-readable alarm annunciator message")
    threshold: float = Field(..., description="Trip threshold value")
    actual_value: float = Field(..., description="Actual observed process value at trip")
    acknowledged: bool = Field(default=False, description="Manual operator acknowledgement flag")
    source: str = Field(default="alarm_engine", description="Alarm generation source")
    bay_id: BayId = Field(default=BayId.BAY_2, description="Associated plant bay")


# ---------------------------------------------------------------------------
# Equipment Definition
# ---------------------------------------------------------------------------

class EquipmentModel(BaseModel):
    """
    Representation of an individual asset within a bay.
    """
    equipment_id: str
    name: str
    equipment_type: str
    bay_id: BayId
    status: EquipmentStatus = EquipmentStatus.RUNNING
    primary_tags: List[str] = Field(default_factory=list)
    description: str = ""
    is_standby_capable: bool = False
    active_work_order: Optional[str] = None


# ---------------------------------------------------------------------------
# Bay State Model
# ---------------------------------------------------------------------------

class BayState(BaseModel):
    """
    Aggregated operational status of a physical equipment bay.
    """
    bay_id: BayId
    name: str
    description: str
    equipment: Dict[str, EquipmentModel] = Field(default_factory=dict)
    telemetry: Dict[str, TelemetryPoint] = Field(default_factory=dict)
    active_alarms: List[AlarmEvent] = Field(default_factory=list)
    status: str = "NORMAL"


# ---------------------------------------------------------------------------
# Plant State Snapshot
# ---------------------------------------------------------------------------

class SimulatorPlantState(BaseModel):
    """
    Comprehensive Canonical Snapshot of the entire Five-Bay Plant.
    """
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    plant_id: str = "PLANT-ETH-01"
    bays: Dict[str, BayState] = Field(default_factory=dict)
    equipment_states: Dict[str, EquipmentStatus] = Field(default_factory=dict)
    telemetry: Dict[str, TelemetryPoint] = Field(default_factory=dict)
    alarms: List[AlarmEvent] = Field(default_factory=list)
    active_scenario: Optional[str] = None
    safety_state: str = "NORMAL"
    utility_state: str = "NORMAL"
    operating_mode: str = "NORMAL"
    is_running: bool = True
    active_case_id: Optional[str] = None
    ml_summaries: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)
